apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: marypearl/checkoutservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: default
spec:
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
